channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=26.0.1
- pip:
  - mlflow==3.9.0
  - cloudpickle==3.1.2
  - numpy==1.26.4
  - pandas==2.2.1
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
